### PR TITLE
Correct quote foreign server name in CREATE FOREIGN TABLE

### LINKED ISSUE #639: Missing server name quoting in CREATE FOREIGN TABLE
```
20230406:18:17:26 gprestore:gpadmin:master:000261-[DEBUG]:-Error encountered when executing statement: CREATE FOREIGN TABLE xxx.yyy (
...
) SERVER my-db-name OPTIONS (schema_name 'qqq',    table_name 'eee') ; Error was: ERROR: syntax error at or near "-" (SQLSTATE 42601)

20230406:18:17:26 gprestore:gpadmin:master:000261-[CRITICAL]:-ERROR: syntax error at or near "-" (SQLSTATE 42601)
```

### PR DESCRIPTION
**Pull request by eshkinkot**
Close #639

### CODE REVIEW

File: backup/queries_table_defs.go [hunk 1]
```diff
@@ -600,7 +600,7 @@ func GetForeignTableDefinitions(connectionPool *dbconn.DBConn) map[uint32]Foreig
 	}
 
 	query := fmt.Sprintf(`
-	SELECT ftrelid, fs.srvname AS ftserver,
+	SELECT ftrelid, pg_catalog.quote_ident(fs.srvname) AS ftserver,
```
Comment (khuddlefish) [inline backup/queries_table_defs.go:603]: We mostly use this as `quote_ident()` rather than `pg_catalog.quote_ident` since we have pg_catalog in our path. It would be better for consistency to follow the pattern we have elsewhere.

Comment (eshkinkot) [reply backup/queries_table_defs.go]: fixed

**Review by khuddlefish — APPROVED** [review]

**Comment by khuddlefish** [comment]
Thanks for the contribution :)
